### ISSUE TITLE
lectureEditor (v5.0.438): Removing the end of a laser pointer action

### ISSUE THREAD

**Issue by maxkratz** [lectureStudio/lectureStudio#394]
**Describe the bug**
Regarding *lectureEditor v5.0.438*:
If I remove the end of a laser pointer action in the recording (e.g., because of an "aahhhm" in the audio), the laser pointer stays in the recording until the end. (It is even possible to do this multiple times.)

**To Reproduce**
1. Record a lecture with *lecturePresenter*.
2. Open the recording with *lectureEditor*.
3. Remove a part of the video in which the laser pointer disappears (using the scissors tool).
4. The laser pointer stays forever.

**Expected behavior**
The *lectureEditor* should not break the disappearance of the laser pointer when cutting a recording.

**Screenshots**
![multiple-lps](https://user-images.githubusercontent.com/20956405/151344074-a0ff2040-5a2b-40b8-a618-7b12ed6a22af.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H2 (19044.1466)

**Additional context**
I've attached a minimalistic recording without editings and the edited file which produces the error.

[Whiteboard-0-2022_01_27-11_44.zip](https://github.com/lectureStudio/lectureStudio/files/7949760/Whiteboard-0-2022_01_27-11_44.zip)
[Whiteboard-0-2022_01_27-11_44-edit.zip](https://github.com/lectureStudio/lectureStudio/files/7949761/Whiteboard-0-2022_01_27-11_44-edit.zip)

**Comment by devopvoid** [comment]
Fixed. Changing existing recordings not required.

**Comment by maxkratz** [comment]
> Fixed. Changing existing recordings not required.

Is the fix already part of the (experimental) release v5.0.445? I've made the following observations with it:

* The cutting of an old (or new) recording does not produce the error anymore.
* An already cut version (which produced the error like the files provided above) is still broken.

**Comment by devopvoid** [comment]
> An already cut version (which produced the error like the files provided above) is still broken.

Right. I missed that. A cut and saved version has the wrong event in it.

**Comment by maxkratz** [comment]
> A cut and saved version has the wrong event in it.

Just to be sure: There is no way fixing the already edited versions right? If this is the case, we can now close this issue :).

**Comment by devopvoid** [comment]
> Just to be sure: There is no way fixing the already edited versions right?

Edited versions can be fixed. But that would take some time. I need the annotations in question (timestamps) and do it "manually". If you have long recordings that need to be fixed, I can do that.

**Comment by maxkratz** [comment]
It was just a general (more theoretical) question. In my case, I've "fixed" the recording by myself by undoing the cutting actions that produced the error. But thank you for the offer!

(I will close the issue now since it is resolved for "new" editings.)
